icon-project/sodax-frontend

- packages/sdk/README.md
- packages/sdk/docs/MONEY_MARKET.md
- packages/sdk/docs/SOLVER.md
- packages/sdk/src/constants.ts
- packages/sdk/src/services/moneyMarket/MoneyMarketService.ts
- packages/sdk/src/services/shared/Erc20Service.ts
- packages/sdk/src/services/solver/SolverService.ts
Changes:
- token allowance
- token approval
- docs update
- money market invariants update
This PR closes #61 .
> feat(sdk) token allowance

- apps/node/src/evm.ts
- apps/node/src/icon.ts
- apps/node/src/stellar.ts
- packages/sdk/src/abis/rate-limit.abi.ts
- packages/sdk/src/constants.ts
- packages/sdk/src/entities/stellar/StellarSpokeProvider.ts
- packages/sdk/src/entities/sui/SuiSpokeProvider.ts
- packages/sdk/src/services/spoke/EvmSpokeService.ts
- packages/sdk/src/services/spoke/IconSpokeService.ts
- packages/sdk/src/services/spoke/SpokeService.ts
- packages/sdk/src/services/spoke/StellarSpokeService.ts
- packages/sdk/src/services/spoke/SuiSpokeService.ts
- packages/sdk/src/types.ts
> fix: rate-limit-sdk

- packages/sdk/src/constants.ts
Update supported money market token configs in sdk to reflect latest state.
> chore(sdk): update money market tokens

- packages/sdk/src/services/moneyMarket/MoneyMarketService.ts
- packages/sdk/src/services/solver/SolverService.ts
- packages/sdk/src/types.ts
Updated in-line docs for solver and money market service of SDK
> chore(sdk): improve solver and money market inline docs

- packages/sdk/README.md
- packages/sdk/docs/MONEY_MARKET.md
- packages/sdk/docs/SOLVER.md
> docs(sdk): markdown docs update

- apps/demo/src/components/mm/lists/SupplyAssetsList.tsx
- apps/demo/src/pages/money-market/page.tsx
- packages/sdk/src/services/spoke/SolanaSpokeService.ts
- packages/sdk/src/services/spoke/SuiSpokeService.ts
- packages/types/src/sui/index.ts
- packages/wallet-sdk/README.md
- packages/wallet-sdk/src/wallet-providers/SuiWalletProvider.ts
> feat: implement sui money market demo

- packages/sdk/src/entities/solana/Configs.ts
- packages/sdk/src/services/spoke/SolanaSpokeService.ts
> feat(solana): reverted to anchor for the best practice

- packages/sdk/src/constants.ts
Updated spoke and solver supported tokens .
> chore(sdk): update supported tokens (spoke, solver)

- apps/demo/src/components/mm/lists/SupplyAssetsList.tsx
- apps/demo/src/components/solver/SwapCard.tsx
- packages/dapp-kit/src/hooks/mm/useUserReservesData.ts
- packages/sdk/src/utils/shared-utils.test.ts
- packages/sdk/src/utils/shared-utils.ts
> feat: add encode address function

- apps/demo/src/components/solver/SwapCard.tsx
> feat: display quote error message

- packages/sdk/README.md
Updated SDK docs to include latest chain integrations.
> docs(sdk): updated to the latest supported chains

- apps/demo/src/constants.ts
- apps/node/src/cosmos.ts
- apps/node/src/evm.ts
- apps/node/src/icon.ts
- apps/node/src/solana.ts
- apps/node/src/stellar.ts
- apps/node/src/sui.ts
- packages/dapp-kit/README.md
- packages/sdk/README.md
- packages/sdk/src/constants.ts
- packages/sdk/src/entities/Sodax.test.ts
- packages/sdk/src/services/solver/SolverService.test.ts
Updated solver URLs in sdk, node and demo app. This PR closes #203 .
> chore(sdk,demo,node): update solver urls

- apps/demo/src/constants.ts
- apps/node/src/cosmos.ts
- apps/node/src/evm.ts
- apps/node/src/icon.ts
- apps/node/src/solana.ts
- apps/node/src/stellar.ts
- apps/node/src/sui.ts
- packages/dapp-kit/README.md
- packages/sdk/README.md
- packages/sdk/src/constants.ts
- packages/sdk/src/entities/Sodax.test.ts
- packages/sdk/src/services/solver/SolverService.test.ts
> feat: update staging solver api endpoint

- apps/demo/src/components/solver/SwapCard.tsx
- apps/demo/src/lib/utils.ts
- apps/node/src/cosmos.ts
- apps/node/src/evm.ts
- apps/node/src/icon.ts
- apps/node/src/solana.ts
- apps/node/src/sonic.ts
- apps/node/src/stellar.ts
- apps/node/src/sui.ts
- packages/dapp-kit/src/hooks/mm/useBorrow.ts
- packages/dapp-kit/src/hooks/mm/useRepay.ts
- packages/dapp-kit/src/hooks/mm/useSupply.ts
- packages/dapp-kit/src/hooks/mm/useWithdraw.ts
- packages/dapp-kit/src/hooks/swap/useCreateIntentOrder.ts
- packages/dapp-kit/src/hooks/swap/useQuote.ts
- packages/dapp-kit/src/hooks/swap/useStatus.ts
- packages/sdk/docs/MONEY_MARKET.md
- packages/sdk/docs/SOLVER.md
- packages/sdk/src/entities/Sodax.test.ts
- packages/sdk/src/guards.ts
- packages/sdk/src/services/intentRelay/IntentRelayApiService.ts
- packages/sdk/src/services/moneyMarket/MoneyMarketService.test.ts
- packages/sdk/src/services/moneyMarket/MoneyMarketService.ts
- packages/sdk/src/services/solver/SolverApiService.test.ts
- packages/sdk/src/services/solver/SolverApiService.ts
- packages/sdk/src/services/solver/SolverService.test.ts
- packages/sdk/src/services/solver/SolverService.ts
- packages/sdk/src/services/spoke/SonicSpokeService.ts
- packages/sdk/src/types.ts
- pnpm-lock.yaml
Refactor:
- SDK error handling
- solver and money market function naming to reflect the action
> refactor(sdk): error handling, primary mm + solver namings

- apps/node/src/wallet-providers/IconWalletProvider.ts
- packages/sdk/src/entities/icon/IconSpokeProvider.ts
- packages/sdk/src/services/spoke/IconSpokeService.ts
- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/wallet-providers/IconWalletProvider.ts
- packages/wallet-sdk/tsup.config.ts
Fix icon imports caused by wallet-sdk and sdk. This PR closes #224 .
> fix(sdk,wallet-sdk): icon imports and tsup

- packages/wallet-sdk/src/constants/xChains.ts
> fix: sonic chain id

- packages/sdk/src/entities/injective/InjectiveSpokeProvider.ts
> fix: is native func in injective

- packages/sdk/README.md
Updated supported wallet interface README doc in SDK
> chore(sdk): update supported wallet interface docs

- apps/web/components/landing/footer.tsx
> feat: update documentation link

- apps/node/src/wallet-providers/InjectiveWalletProvider.ts
- packages/sdk/src/entities/injective/InjectiveSpokeProvider.ts
- packages/types/src/injective/index.ts
- packages/wallet-sdk/src/wallet-providers/InjectiveWalletProvider.ts
> refactor(wallet-sdk, sdk): update getRawTransaction to return a Promise

- apps/web/app/layout.tsx
- apps/web/app/wallets/page.tsx
- apps/web/app/wallets/wallet-item.tsx
- apps/web/package.json
- apps/web/providers/constants.ts
- apps/web/providers/providers.tsx
- packages/wallet-sdk/src/xchains/icon/IconXService.ts
- pnpm-lock.yaml
> fix: wallet connect on nextjs

- packages/sdk/README.md
Replaced xWagmi with Wallet SDK in the docs.
> docs(SDK): replace xWagmi with Wallet SDK

- packages/sdk/docs/SOLVER.md
- packages/sdk/src/entities/Sodax.test.ts
- packages/sdk/src/services/solver/SolverService.test.ts
- packages/sdk/src/services/solver/SolverService.ts
Sets default solver config partner fee as default swap input param.
> fix(sdk): solver partner fee in swap

- apps/demo/package.json
- apps/demo/src/components/ui/tabs.tsx
- apps/demo/src/constants.ts
- apps/demo/src/pages/solver/page.tsx
- apps/demo/src/providers.tsx
- apps/demo/src/zustand/useAppStore.tsx
- apps/node/src/bnusd-migration.test.ts
- apps/node/src/stellar.ts
- apps/node/src/sui.ts
- apps/node/src/wallet-providers/IconWalletProvider.ts
- packages/sdk/src/guards.ts
- packages/sdk/src/services/migration/MigrationService.ts
- packages/sdk/src/services/solver/SolverService.ts
- pnpm-lock.yaml
> feat: add environment switcher in solver

- apps/demo/src/components/solver/OrderStatus.tsx
- apps/demo/src/components/solver/SwapCard.tsx
- apps/demo/src/pages/solver/page.tsx
- packages/dapp-kit/src/hooks/swap/useSwap.ts
- packages/sdk/docs/SOLVER.md
- packages/sdk/src/services/intentRelay/IntentRelayApiService.ts
- packages/sdk/src/services/solver/SolverService.ts
Updated solver swap (create intent and submit) response type to include relevant info required for frontends to have easier time proceeding with actions.
> refactor(sdk,demo,dapp-kit): solver swap response structure

- packages/sdk/src/services/solver/SolverService.ts
- packages/sdk/src/utils/shared-utils.test.ts
- packages/sdk/src/utils/shared-utils.ts
Fixes fee logic on quote request for all quote types.
> fix(sdk): solver quote fee logic

- packages/sdk/src/services/solver/SolverService.ts
- packages/sdk/src/services/spoke/SonicSpokeService.ts
Refactored sonic intents to be native and direct (user wallet directly to intent contract). Also fixed allowance and approval for it.
> refactor(sdk): sonic intent to native execution

- apps/demo/src/components/mm/lists/BorrowButton.tsx
- apps/demo/src/components/mm/lists/SupplyAssetsList.tsx
- apps/demo/src/components/mm/lists/WithdrawButton.tsx
- apps/node/src/moneymarket.ts
- packages/sdk/src/entities/Sodax.test.ts
- packages/sdk/src/moneyMarket/MoneyMarketDataService.ts
- packages/sdk/src/moneyMarket/MoneyMarketService.test.ts
- packages/sdk/src/moneyMarket/MoneyMarketService.ts
- packages/sdk/src/services/hub/WalletAbstractionService.ts
- packages/sdk/src/services/solver/SolverService.test.ts
- packages/sdk/src/services/solver/SolverService.ts
- packages/sdk/src/services/spoke/SonicSpokeService.ts
- packages/sdk/src/services/spoke/SpokeService.ts
- packages/sdk/src/utils/shared-utils.test.ts
- packages/sdk/src/utils/shared-utils.ts
Refactors money market collateral and debt token location to end in original sonic user wallet. It also addresses bnUSD info retrieval in demo.
> refactor(sdk): mm sonic user wallet as token holder

- packages/sdk/docs/SOLVER.md
- packages/sdk/src/constants.ts
- packages/sdk/src/services/solver/SolverService.test.ts
- packages/sdk/src/services/solver/SolverService.ts
Introduces swap/solver get method to retrieve deadline based off hub chain block timestamp.
> feat(sdk): swap deadline

- packages/sdk/src/constants.ts
Updates SUI asset manager ID to new one.
> chore(sdk): update sui asset manager id

- packages/sdk/src/constants.ts
> chore(sdk): update asset manager IDs in spokeChainConfig

- apps/node/src/sui.ts
- packages/sdk/src/constants.ts
- packages/sdk/src/entities/sui/SuiSpokeProvider.ts
- packages/sdk/src/services/spoke/SuiSpokeService.ts
- packages/sdk/src/services/spoke/index.ts
- packages/sdk/src/types.ts
Dynamic SUI asset manager address retrieval. This solves Sui smart contract upgrades compatibility issue.
> feat(sdk): dynamic sui asset manager

- packages/sdk/src/services/migration/MigrationService.ts
> feat(sdk): enhance migration service to validate EVM allowances

- apps/node/package.json
- apps/node/src/bnusd-migration.test.ts
- apps/node/src/sui-wallet-provider.ts
- packages/sdk/src/entities/sui/SuiSpokeProvider.ts
- packages/sdk/src/services/spoke/SpokeService.ts
- packages/sdk/src/services/spoke/StellarSpokeService.ts
- pnpm-lock.yaml
Fixes Sui and Stellar migrate bnUSD issues.
> fix(sdk): sui stellar migrate bnusd

- apps/demo/src/lib/utils.ts
- apps/demo/src/pages/bridge/page.tsx
- packages/dapp-kit/README.md
- packages/dapp-kit/src/hooks/shared/useRequestTrustline.ts
- packages/dapp-kit/src/hooks/shared/useStellarTrustlineCheck.ts
- packages/sdk/docs/BRIDGE.md
- packages/sdk/docs/MIGRATION.md
- packages/sdk/docs/MONEY_MARKET.md
- packages/sdk/docs/SOLVER.md
- packages/sdk/src/services/spoke/StellarSpokeService.test.ts
- packages/sdk/src/services/spoke/StellarSpokeService.ts
Update:
- Stellar trustline docs
- Stellar trustline tests
- Demo: Bridge stellar trustline
-
> test: stellar trustline

- apps/demo/package.json
- apps/demo/src/index.tsx
- apps/demo/src/zustand/useAppStore.tsx
- apps/demo/vite.config.ts
- packages/sdk/package.json
- packages/wallet-sdk-core/src/wallet-providers/InjectiveWalletProvider.ts
- packages/wallet-sdk-react/src/useXWagmiStore.tsx
- packages/wallet-sdk-react/src/xchains/injective/InjectiveXService.ts
- pnpm-lock.yaml
> feat: support keplr wallet

- apps/demo/src/pages/money-market/page.tsx
- apps/web/components/landing/herosection.tsx
- apps/web/components/shared/route-tabs.tsx
- packages/wallet-sdk-react/src/hooks/index.ts
- packages/wallet-sdk-react/src/hooks/useXSignMessage.ts
> Feat: sign terms

- apps/web/app/(apps)/migrate/_components/icxsoda-migration.tsx
- apps/web/app/(apps)/swap/_components/swap-confirm-dialog.tsx
- apps/web/app/(apps)/swap/page.tsx
- apps/web/components/shared/wallet-modal2/wallet-modal.tsx
- apps/web/hooks/useTokenPrice.ts
- packages/sdk/docs/SOLVER.md
- packages/sdk/src/entities/Sodax.test.ts
- packages/sdk/src/services/solver/SolverService.test.ts
- packages/sdk/src/services/solver/SolverService.ts
> fix: swap bugs

- apps/web/app/(apps)/swap/_components/swap-confirm-dialog.tsx
> Fix: swap bug quote

- packages/sdk/src/entities/icon/IconSpokeProvider.ts
- packages/sdk/src/services/spoke/IconSpokeService.ts
- packages/wallet-sdk-core/src/wallet-providers/IconWalletProvider.ts
- packages/wallet-sdk-react/src/xchains/icon/IconXService.ts
> fix: fixed Icon SDK for node applications
